 $(".show").click(function(){
          $('.Osnova').css('display','flex')
          $('.start').css('display','none')
             })
    $('#i1').click(function(){
      $('.lastPart').css('display','flex');
      $('.Osnova').css('display','none')
      $('.card3').css('display','flex')
    })
    $('#i2').click(function(){
      $('.lastPart').css('display','flex');
      $('.Osnova').css('display','none')
      $('.card4').css('display','flex')
    })
    $('#i3').click(function(){
      $('.lastPart').css('display','flex');
      $('.Osnova').css('display','none')
      $('.card5').css('display','flex')
    })
    $('#i5').click(function(){
      $('.lastPart').css('display','flex');
      $('.Osnova').css('display','none')
      $('.card6').css('display','flex')
    })
    $('#i6').click(function(){
      $('.lastPart').css('display','flex');
      $('.Osnova').css('display','none')
      $('.card7').css('display','flex')
    })
    $('.none').click(function(){
         $('.lastPart').css('display','none');
         $('.Osnova').css('display','flex');
         $('.card3').css('display','none');
         $('.card4').css('display','none');
         $('.card5').css('display','none');
         $('.card6').css('display','none');
         $('.card7').css('display','none');
    })
   
